kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: email-notification
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: email-notification
      email_configs:
      - to: ulrichsun@gmail.com
        send_resolved: true
        from: ulrichsun@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: ulrichsun@gmail.com
        auth_identity: ulrichsun@gmail.com
        auth_password: ovclhkmlwetpqhto
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://tchat.its-nh.com:8443/hooks/y6zksqx3qjbrjqo9ucpfu3np6r
        channel: '#kubernetes'
